### PR TITLE
Add pie chart animation and install screen

### PR DESCRIPTION
**Pull request by mushon**
made the pie animation work, **excited!!!**

### CODE REVIEW

**Comment by mushon** [comment]
@amitaibu I would appreciate you merging this into gh-pages soonish

**Comment by amitaibu** [comment]
@mushon please attach screenshot of how it's supposed to look.

**Comment by mushon** [comment]
screen shot 2013-11-07 at 9 03 51 am

**Comment by mushon** [comment]
it is currently not hooked into the button, that's what I meant in the inline comments

**Comment by amitaibu** [comment]
Ok, got it.

**Comment by amitaibu** [comment]
@ceoaliongroo we probably need to move some of the code into the `addMarker` directive

**Comment by amitaibu** [comment]
Merged.

**Pull request closed without merging**
