### PR TITLE
Design elements

### PR DESCRIPTION
**Pull request by mushon**
@amitaibu:
1. I just pushed my latest changes to my branch
2. [ ] I added the edit-place button which needs to be hooked in to choosing between multiple 4Sq places or adding a new one.
3. [ ] I still need a marker for my current location (the red ring) and a button for the orientation the gray arrow on this image: https://f.cloud.github.com/assets/27123/1132408/f3f80224-1bc9-11e3-927c-cb299b5a673e.png
4. [ ] I also need the add button to function as the marker there, like in this image: https://f.cloud.github.com/assets/27123/1132397/f39ef3fa-1bc9-11e3-8a65-4a38160a9861.png
5. [ ] when the map is dragged I would like the placemark to "hover above the map" and for a ring under it to mark the point of reference. Add the code and I'll style it.

### CODE REVIEW

**Comment by niryariv** [comment]
@mushon i'll add 3 & 4 as issues. re "edit place" and orientation I suggest we keep them out of this iteration in order to make the oct release 17th goal - sounds ok?

**Comment by amitaibu** [comment]
Merged "Designed the place your pin screen"

**Comment by mushon** [comment]
@amitaibu here's some more for you to pull.
Please note:
- I created two classes that should be dynamically added as you type:
  - if char-count < 10, add .a-lot to .char-count
  - if char-count <0. add .too-much to .confirm
- Other than that, please note the need to make the place-mark & place-name clickable in case the user wants to choose a different place corresponding with the same geolocation (both in this stage and in the place-marker stage)
- I will do the fine tuning of how it looks on mobile devices with you guys tomorrow in your office.

**Comment by amitaibu** [comment]
Merged.

**Pull request closed without merging**
