### PR TITLE
Use icon current location.

### PR DESCRIPTION
**Pull request by ceoaliongroo**
#130

Positioned the current position.
NOTE: Need to finish work with the element and parent css.

### CODE REVIEW

**Comment by ceoaliongroo** [comment]
@mushon please, could you check the css? 

thanks

**Comment by amitaibu** [comment]
localhost_9000___

**Comment by mushon** [comment]
by this you mean you fixed it? Or you didn't see the error?
Yesterday the marker was attaching itself to other markers in a pretty inconsistent manner.
Oh, and btw, the marker is supposed to be white, you're probably not up to date with my changes.

## 

Mushon Zer-Aviv
Mushon.com (http://Mushon.com) | Shual.com (http://Shual.com) | @Mushon (http://twitter.com/mushon)

**Comment by amitaibu** [comment]
> by this you mean you fixed it?

Yes.

pushed to gh-pages.

> Oh, and btw, the marker is supposed to be white, you're probably not up to date with my changes.

Were using the provided image. Anyway, it's no just about CSS so you can take it form here.

**Pull request closed without merging**
